# Generated by Django 6.0.4 on 2026-04-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
        ('promotions', '0001_initial'),
        ('supermarkets', '0004_alter_supermarket_options_alter_supermarket_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'promocao', 'verbose_name_plural': 'promocoes'},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criada em'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(verbose_name='data de fim'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativa'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promotional_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco promocional'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(verbose_name='data de inicio'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='supermarkets.supermarket', verbose_name='supermercado'),
        ),
    ]
