# Generated by Django 6.0.4 on 2026-04-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
        ('supermarkets', '0004_alter_supermarket_options_alter_supermarket_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productprice',
            options={'ordering': ['price'], 'verbose_name': 'preco do produto', 'verbose_name_plural': 'precos dos produtos'},
        ),
        migrations.AlterField(
            model_name='productprice',
            name='available',
            field=models.BooleanField(default=True, verbose_name='disponivel'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preco antigo'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='produto'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='supermarkets.supermarket', verbose_name='supermercado'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
