# Generated by Django 6.0.4 on 2026-04-28 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supermarkets', '0002_supermarket_cnpj_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupermarketUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietario'), ('manager', 'Gerente'), ('staff', 'Funcionario')], default='staff', max_length=20, verbose_name='funcao')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='supermarkets.supermarket', verbose_name='supermercado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supermarket_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'usuario de supermercado',
                'verbose_name_plural': 'usuarios de supermercados',
                'ordering': ['supermarket__name', 'user__username'],
            },
        ),
    ]
