# Generated by Django 6.0.4 on 2026-04-28 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('default_street', models.CharField(blank=True, max_length=150, verbose_name='rua padrao')),
                ('default_number', models.CharField(blank=True, max_length=30, verbose_name='numero padrao')),
                ('default_district', models.CharField(blank=True, max_length=100, verbose_name='bairro padrao')),
                ('default_city', models.CharField(blank=True, max_length=100, verbose_name='cidade padrao')),
                ('default_complement', models.CharField(blank=True, max_length=150, verbose_name='complemento padrao')),
                ('default_reference', models.CharField(blank=True, max_length=150, verbose_name='referencia padrao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de cliente',
                'verbose_name_plural': 'perfis de clientes',
                'ordering': ['user__first_name', 'user__email'],
            },
        ),
    ]
