# Generated by Django 6.0.4 on 2026-04-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0002_supermarket_cnpj_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarket',
            name='default_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxa padrao de entrega'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='delivery_available',
            field=models.BooleanField(default=False, verbose_name='entrega disponivel'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='observacoes de entrega'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='free_delivery_minimum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor minimo para entrega gratis'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='pickup_available',
            field=models.BooleanField(default=True, verbose_name='retirada disponivel'),
        ),
    ]
