# Generated by Django 6.0.4 on 2026-04-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarkets', '0003_alter_supermarket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supermarket',
            options={'ordering': ['name'], 'verbose_name': 'supermercado', 'verbose_name_plural': 'supermercados'},
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='address',
            field=models.CharField(max_length=255, verbose_name='endereco'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='city',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='district',
            field=models.CharField(max_length=100, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='supermarkets/logos/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='name',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
