# Generated by Django 6.0.4 on 2026-04-28 11:30

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('supermarkets', '0002_supermarket_cnpj_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=orders.models.generate_order_code, editable=False, max_length=12, unique=True, verbose_name='codigo')),
                ('customer_name', models.CharField(max_length=150, verbose_name='nome do cliente')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='telefone do cliente')),
                ('customer_address', models.CharField(blank=True, max_length=255, verbose_name='endereco do cliente')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('reviewing', 'Em analise'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('finished', 'Finalizado')], default='pending', max_length=20, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('supermarket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='supermarkets.supermarket', verbose_name='supermercado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=150, verbose_name='nome do produto')),
                ('product_brand_snapshot', models.CharField(blank=True, max_length=100, verbose_name='marca do produto')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preco unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'ordering': ['product_name_snapshot'],
            },
        ),
    ]
