# Generated by Django 6.0.4 on 2026-04-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='observacoes internas'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pendente'), ('reviewing', 'Em analise'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('finished', 'Finalizado')], max_length=20, verbose_name='status anterior')),
                ('new_status', models.CharField(choices=[('pending', 'Pendente'), ('reviewing', 'Em analise'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('finished', 'Finalizado')], max_length=20, verbose_name='novo status')),
                ('note', models.TextField(blank=True, verbose_name='observacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'historico de status',
                'verbose_name_plural': 'historicos de status',
                'ordering': ['-created_at'],
            },
        ),
    ]
