# Generated by Django 6.0.4 on 2026-04-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_internal_notes_orderstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_complement',
            field=models.CharField(blank=True, max_length=150, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='taxa de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_reference',
            field=models.CharField(blank=True, max_length=150, verbose_name='referencia'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=150, verbose_name='rua'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total final'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_method',
            field=models.CharField(choices=[('pickup', 'Retirada no supermercado'), ('delivery', 'Entrega em casa'), ('arrange', 'Combinar com o mercado')], default='arrange', max_length=20, verbose_name='tipo de atendimento'),
        ),
        migrations.AddField(
            model_name='order',
            name='products_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total dos produtos'),
        ),
    ]
